// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__, useDataEnv } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/levelset_v2/PlasmicGlobalContextsProvider";

import { PlasmicDiscipline } from "../components/plasmic/levelset_v_2/PlasmicDiscipline";
import { useRouter } from "next/router";
import { Box, Typography } from "@mui/material";

// Location numbers for which discipline should be disabled (except for Levelset Admin)
const DISCIPLINE_DISABLED_LOCATIONS = ['05467'];

function AccessDeniedMessage() {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '60vh',
        padding: 4,
        textAlign: 'center',
      }}
    >
      <Typography
        variant="h4"
        sx={{
          fontFamily: '"Satoshi", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          fontWeight: 700,
          color: '#111827',
          marginBottom: 2,
        }}
      >
        You don&apos;t have access to this page
      </Typography>
      <Typography
        sx={{
          fontFamily: '"Satoshi", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
          fontSize: 16,
          color: '#6b7280',
          maxWidth: 400,
        }}
      >
        The discipline features are not available for your location. Please contact your administrator if you believe this is an error.
      </Typography>
    </Box>
  );
}

function DisciplineContent() {
  const dataEnv = useDataEnv?.() || {};
  const locationContext = (dataEnv as any)?.locationContext || {};
  const auth = (dataEnv as any)?.auth || {};
  
  const selectedLocationNumber = locationContext?.selectedLocationNumber || null;
  const userRole = auth?.role || '';
  
  // Check if discipline should be blocked for this location
  const isDisciplineDisabled = DISCIPLINE_DISABLED_LOCATIONS.includes(selectedLocationNumber ?? '');
  const isLevelsetAdmin = userRole === 'Levelset Admin';
  
  // Show access denied for disabled locations unless user is Levelset Admin
  if (isDisciplineDisabled && !isLevelsetAdmin) {
    return <AccessDeniedMessage />;
  }

  return <PlasmicDiscipline />;
}

function Discipline() {
  // Use PlasmicDiscipline to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicDiscipline are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicDiscipline is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <DisciplineContent />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Discipline;
