/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eNCsaJXBZ9ykYnmvxCb8Zx
// Component: X7Sn6AWMY-7d

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import MenuNavigation from "../../MenuNavigation"; // plasmic-import: eJlFBj1x_mCN/component
import DashboardSubmenu from "../../DashboardSubmenu"; // plasmic-import: DnrJ08NISsSS/component
import { RedirectIf } from "../../CodeComponents/RedirectIf"; // plasmic-import: gEWHFHS2fu7I/codeComponent
import LevelsetButton from "../../LevelsetButton"; // plasmic-import: u704oB_4BUvT/component
import { FohBohSlider } from "../../CodeComponents/FohBohSlider"; // plasmic-import: 6LJFyJRGdgX4/codeComponent
import { PositionButtons } from "../../CodeComponents/PositionButtons"; // plasmic-import: tQU-ID6-K3GO/codeComponent
import { ScoreboardTable } from "../../CodeComponents/ScoreboardTable"; // plasmic-import: EURkS6Dky8BE/codeComponent
import { PEARubric } from "../../CodeComponents/PEARubric"; // plasmic-import: Kl-hD0pLbIQ_/codeComponent
import { PEAClassic } from "../../CodeComponents/PEAClassic"; // plasmic-import: jAb7H8eOs0Ht/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../levelset_v2/plasmic_levelset_v2.module.css"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectcss
import sty from "./PlasmicPeaClassic.module.css"; // plasmic-import: X7Sn6AWMY-7d/css

import ArrowLeftIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__ArrowLeft"; // plasmic-import: CFGagD1izIUw/icon
import IconIcon from "../levelset_tabs/icons/PlasmicIcon__Icon"; // plasmic-import: CEbmjO_n9jaW/icon

createPlasmicElementProxy;

export type PlasmicPeaClassic__VariantMembers = {};
export type PlasmicPeaClassic__VariantsArgs = {};
type VariantPropType = keyof PlasmicPeaClassic__VariantsArgs;
export const PlasmicPeaClassic__VariantProps = new Array<VariantPropType>();

export type PlasmicPeaClassic__ArgsType = {};
type ArgPropType = keyof PlasmicPeaClassic__ArgsType;
export const PlasmicPeaClassic__ArgProps = new Array<ArgPropType>();

export type PlasmicPeaClassic__OverridesType = {
  root?: Flex__<"div">;
  menuNavigation?: Flex__<typeof MenuNavigation>;
  redirectIf?: Flex__<typeof RedirectIf>;
  levelsetButton?: Flex__<typeof LevelsetButton>;
  svg?: Flex__<"svg">;
  verticalStack?: Flex__<"div">;
  bohSlider?: Flex__<typeof FohBohSlider>;
  positionButtons?: Flex__<typeof PositionButtons>;
  peaScoreboardTable?: Flex__<typeof ScoreboardTable>;
  verticalStack2?: Flex__<"div">;
  peaRubric?: Flex__<typeof PEARubric>;
  verticalStack3?: Flex__<"div">;
  peaClassic?: Flex__<typeof PEAClassic>;
};

export interface DefaultPeaClassicProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPeaClassic__RenderFunc(props: {
  variants: PlasmicPeaClassic__VariantsArgs;
  args: PlasmicPeaClassic__ArgsType;
  overrides: PlasmicPeaClassic__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "menuNavigation.headerLocationId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "menuNavigation.firstName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.first_name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "menuNavigation.userRole",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.role;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "menuNavigation.lastName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.last_name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPeaClassic.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPeaClassic.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPeaClassic.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <MenuNavigation
          data-plasmic-name={"menuNavigation"}
          data-plasmic-override={overrides.menuNavigation}
          className={classNames("__wab_instance", sty.menuNavigation)}
          firstName={generateStateValueProp($state, [
            "menuNavigation",
            "firstName"
          ])}
          headerLocationId={generateStateValueProp($state, [
            "menuNavigation",
            "headerLocationId"
          ])}
          lastName={generateStateValueProp($state, [
            "menuNavigation",
            "lastName"
          ])}
          onFirstNameChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "firstName"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onHeaderLocationIdChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "headerLocationId"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLastNameChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "lastName"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onUserRoleChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "userRole"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          userRole={generateStateValueProp($state, [
            "menuNavigation",
            "userRole"
          ])}
        />

        <RedirectIf
          data-plasmic-name={"redirectIf"}
          data-plasmic-override={overrides.redirectIf}
          className={classNames("__wab_instance", sty.redirectIf)}
          condition={(() => {
            try {
              return $ctx.auth && !!$ctx.auth.email;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
          onFalse={async () => {
            const $steps = {};

            $steps["goToLoginPage"] = true
              ? (() => {
                  const actionArgs = { destination: `/auth/login` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      __nextRouter?.push(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToLoginPage"] != null &&
              typeof $steps["goToLoginPage"] === "object" &&
              typeof $steps["goToLoginPage"].then === "function"
            ) {
              $steps["goToLoginPage"] = await $steps["goToLoginPage"];
            }
          }}
        >
          <div className={classNames(projectcss.all, sty.freeBox__evXNr)}>
            <div className={classNames(projectcss.all, sty.freeBox__okPhs)}>
              <div className={classNames(projectcss.all, sty.freeBox__rv6F)}>
                <div className={classNames(projectcss.all, sty.freeBox__ode13)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zh3Ru)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yBey6
                      )}
                    >
                      {"PEA Dashboard - Classic View"}
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qFcI)}
                  >
                    <LevelsetButton
                      data-plasmic-name={"levelsetButton"}
                      data-plasmic-override={overrides.levelsetButton}
                      className={classNames(
                        "__wab_instance",
                        sty.levelsetButton
                      )}
                      color={"brand"}
                      onClick={async event => {
                        const $steps = {};

                        $steps["goToPositionalExcellence"] = true
                          ? (() => {
                              const actionArgs = {
                                destination: `/positional-excellence`
                              };
                              return (({ destination }) => {
                                if (
                                  typeof destination === "string" &&
                                  destination.startsWith("#")
                                ) {
                                  document
                                    .getElementById(destination.substr(1))
                                    .scrollIntoView({ behavior: "smooth" });
                                } else {
                                  __nextRouter?.push(destination);
                                }
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["goToPositionalExcellence"] != null &&
                          typeof $steps["goToPositionalExcellence"] ===
                            "object" &&
                          typeof $steps["goToPositionalExcellence"].then ===
                            "function"
                        ) {
                          $steps["goToPositionalExcellence"] =
                            await $steps["goToPositionalExcellence"];
                        }
                      }}
                      showStartIcon={true}
                      size={"compact"}
                      startIcon={
                        <ArrowLeftIcon
                          data-plasmic-name={"svg"}
                          data-plasmic-override={overrides.svg}
                          className={classNames(projectcss.all, sty.svg)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fWt60
                        )}
                      >
                        {"Back to SmartView"}
                      </div>
                    </LevelsetButton>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___4Zgo)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hnEo3
                    )}
                  >
                    {
                      "Filter using the position buttons and click a Team Member to see their recent ratings.."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d5U67
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#000000" }}
                      >
                        {"Coming soon!"}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__tqxeq)}>
            <div className={classNames(projectcss.all, sty.freeBox__oDVs)}>
              <div
                data-plasmic-name={"verticalStack"}
                data-plasmic-override={overrides.verticalStack}
                className={classNames(projectcss.all, sty.verticalStack)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aMeQs
                  )}
                >
                  {"Employees"}
                </div>
                <FohBohSlider
                  data-plasmic-name={"bohSlider"}
                  data-plasmic-override={overrides.bohSlider}
                  className={classNames("__wab_instance", sty.bohSlider)}
                />

                <PositionButtons
                  data-plasmic-name={"positionButtons"}
                  data-plasmic-override={overrides.positionButtons}
                  className={classNames("__wab_instance", sty.positionButtons)}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___0SiXc)}
                >
                  <ScoreboardTable
                    data-plasmic-name={"peaScoreboardTable"}
                    data-plasmic-override={overrides.peaScoreboardTable}
                    activeGroup={"FOH"}
                    bundleUrl={
                      "https://storage.googleapis.com/trainingapp-assets/snapshots/buda/all.json"
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.peaScoreboardTable
                    )}
                    currentTab={(() => {
                      try {
                        return undefined;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "FOH";
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"verticalStack2"}
                data-plasmic-override={overrides.verticalStack2}
                className={classNames(projectcss.all, sty.verticalStack2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mFycJ
                  )}
                >
                  {"Disciplinary Actions"}
                </div>
                <PEARubric
                  data-plasmic-name={"peaRubric"}
                  data-plasmic-override={overrides.peaRubric}
                  className={classNames("__wab_instance", sty.peaRubric)}
                />
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"verticalStack3"}
            data-plasmic-override={overrides.verticalStack3}
            className={classNames(projectcss.all, sty.verticalStack3)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___5RvN7)}>
              <div className={classNames(projectcss.all, sty.freeBox__cVeu1)}>
                <PEAClassic
                  data-plasmic-name={"peaClassic"}
                  data-plasmic-override={overrides.peaClassic}
                  className={classNames("__wab_instance", sty.peaClassic)}
                  defaultArea={"FOH"}
                  defaultTab={"overview"}
                  density={"comfortable"}
                  locationId={"67e00fb2-29f5-41ce-9c1c-93e2f7f392dd"}
                  maxWidth={"100%"}
                  orgId={"54b9864f-9df9-4a15-a209-7b99e1c274f4"}
                  width={"100%"}
                />
              </div>
            </div>
          </div>
        </RedirectIf>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "menuNavigation",
    "redirectIf",
    "levelsetButton",
    "svg",
    "verticalStack",
    "bohSlider",
    "positionButtons",
    "peaScoreboardTable",
    "verticalStack2",
    "peaRubric",
    "verticalStack3",
    "peaClassic"
  ],
  menuNavigation: ["menuNavigation"],
  redirectIf: [
    "redirectIf",
    "levelsetButton",
    "svg",
    "verticalStack",
    "bohSlider",
    "positionButtons",
    "peaScoreboardTable",
    "verticalStack2",
    "peaRubric",
    "verticalStack3",
    "peaClassic"
  ],
  levelsetButton: ["levelsetButton", "svg"],
  svg: ["svg"],
  verticalStack: [
    "verticalStack",
    "bohSlider",
    "positionButtons",
    "peaScoreboardTable"
  ],
  bohSlider: ["bohSlider"],
  positionButtons: ["positionButtons"],
  peaScoreboardTable: ["peaScoreboardTable"],
  verticalStack2: ["verticalStack2", "peaRubric"],
  peaRubric: ["peaRubric"],
  verticalStack3: ["verticalStack3", "peaClassic"],
  peaClassic: ["peaClassic"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  menuNavigation: typeof MenuNavigation;
  redirectIf: typeof RedirectIf;
  levelsetButton: typeof LevelsetButton;
  svg: "svg";
  verticalStack: "div";
  bohSlider: typeof FohBohSlider;
  positionButtons: typeof PositionButtons;
  peaScoreboardTable: typeof ScoreboardTable;
  verticalStack2: "div";
  peaRubric: typeof PEARubric;
  verticalStack3: "div";
  peaClassic: typeof PEAClassic;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPeaClassic__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPeaClassic__VariantsArgs;
    args?: PlasmicPeaClassic__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPeaClassic__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPeaClassic__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPeaClassic__ArgProps,
          internalVariantPropNames: PlasmicPeaClassic__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPeaClassic__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPeaClassic";
  } else {
    func.displayName = `PlasmicPeaClassic.${nodeName}`;
  }
  return func;
}

export const PlasmicPeaClassic = Object.assign(
  // Top-level PlasmicPeaClassic renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuNavigation: makeNodeComponent("menuNavigation"),
    redirectIf: makeNodeComponent("redirectIf"),
    levelsetButton: makeNodeComponent("levelsetButton"),
    svg: makeNodeComponent("svg"),
    verticalStack: makeNodeComponent("verticalStack"),
    bohSlider: makeNodeComponent("bohSlider"),
    positionButtons: makeNodeComponent("positionButtons"),
    peaScoreboardTable: makeNodeComponent("peaScoreboardTable"),
    verticalStack2: makeNodeComponent("verticalStack2"),
    peaRubric: makeNodeComponent("peaRubric"),
    verticalStack3: makeNodeComponent("verticalStack3"),
    peaClassic: makeNodeComponent("peaClassic"),

    // Metadata about props expected for PlasmicPeaClassic
    internalVariantProps: PlasmicPeaClassic__VariantProps,
    internalArgProps: PlasmicPeaClassic__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "PEA Dashboard | Levelset",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPeaClassic;
/* prettier-ignore-end */
