/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eNCsaJXBZ9ykYnmvxCb8Zx
// Component: -vnBKJaatlPo

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import MenuNavigation from "../../MenuNavigation"; // plasmic-import: eJlFBj1x_mCN/component
import DashboardSubmenu from "../../DashboardSubmenu"; // plasmic-import: DnrJ08NISsSS/component
import { LoadingBoundary } from "@plasmicpkgs/plasmic-basic-components";
import { LottieWrapper } from "@plasmicpkgs/lottie-react";
import { RedirectIf } from "../../CodeComponents/RedirectIf"; // plasmic-import: gEWHFHS2fu7I/codeComponent
import { DisciplineTable } from "../../CodeComponents/DisciplineTable"; // plasmic-import: Gsr7FZewgF56/codeComponent
import { DisciplineActionsTable } from "../../CodeComponents/DisciplineActionsTable"; // plasmic-import: gO99exJZ_N-6/codeComponent
import { MuiDrawerV2 } from "../../CodeComponents/MuiDrawerV2"; // plasmic-import: hoSoBbznWutx/codeComponent
import { DrawerTabContainer } from "../../CodeComponents/DrawerTabContainer"; // plasmic-import: 3_XXEMijZcI9/codeComponent
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../levelset_v2/plasmic_levelset_v2.module.css"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectcss
import sty from "./PlasmicDiscipline.module.css"; // plasmic-import: -vnBKJaatlPo/css

createPlasmicElementProxy;

export type PlasmicDiscipline__VariantMembers = {};
export type PlasmicDiscipline__VariantsArgs = {};
type VariantPropType = keyof PlasmicDiscipline__VariantsArgs;
export const PlasmicDiscipline__VariantProps = new Array<VariantPropType>();

export type PlasmicDiscipline__ArgsType = {};
type ArgPropType = keyof PlasmicDiscipline__ArgsType;
export const PlasmicDiscipline__ArgProps = new Array<ArgPropType>();

export type PlasmicDiscipline__OverridesType = {
  root?: Flex__<"div">;
  menuNavigation?: Flex__<typeof MenuNavigation>;
  loadingBoundary?: Flex__<typeof LoadingBoundary>;
  lottie?: Flex__<typeof LottieWrapper>;
  redirectIf?: Flex__<typeof RedirectIf>;
  verticalStack?: Flex__<"div">;
  disciplineTable?: Flex__<typeof DisciplineTable>;
  verticalStack2?: Flex__<"div">;
  disciplineActionsTable?: Flex__<typeof DisciplineActionsTable>;
  drawerV2Mui?: Flex__<typeof MuiDrawerV2>;
  drawerTabContainer?: Flex__<typeof DrawerTabContainer>;
  content3?: Flex__<"div">;
  textAndSupportingText3?: Flex__<"div">;
  textAndOnlineIndicator2?: Flex__<"div">;
  text3?: Flex__<"div">;
  supportingText3?: Flex__<"div">;
};

export interface DefaultDisciplineProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDiscipline__RenderFunc(props: {
  variants: PlasmicDiscipline__VariantsArgs;
  args: PlasmicDiscipline__ArgsType;
  overrides: PlasmicDiscipline__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selectedEmployee",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "initialProfileTab",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "tab4"
      },
      {
        path: "menuNavigation.headerLocationId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``
      },
      {
        path: "menuNavigation.firstName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.first_name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "menuNavigation.userRole",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.role;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "menuNavigation.lastName",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $ctx.auth.last_name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "drawerV2Mui.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.drawerOpen;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })()
      },
      {
        path: "drawerOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    discActionsRubric: usePlasmicDataOp(() => {
      return {
        sourceId: "wGi39M1g3x2KnbXK4J4Gyq",
        opId: "16d21f59-38ef-44d0-868d-b5a0c1746cfa",
        userArgs: {},
        cacheKey: `plasmic.$.16d21f59-38ef-44d0-868d-b5a0c1746cfa.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    employeesDiscQuery: usePlasmicDataOp(() => {
      return {
        sourceId: "wGi39M1g3x2KnbXK4J4Gyq",
        opId: "c3bd2802-6689-478d-a8a6-846360d08597",
        userArgs: {
          filters: [$state.selectedEmployee?.id]
        },
        cacheKey: `plasmic.$.c3bd2802-6689-478d-a8a6-846360d08597.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    directorsQuery: usePlasmicDataOp(() => {
      return {
        sourceId: "wGi39M1g3x2KnbXK4J4Gyq",
        opId: "9fa90f8d-dff1-43d3-a2db-4a18759d94d6",
        userArgs: {},
        cacheKey: `plasmic.$.9fa90f8d-dff1-43d3-a2db-4a18759d94d6.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    activeAppUser: usePlasmicDataOp(() => {
      return {
        sourceId: "wGi39M1g3x2KnbXK4J4Gyq",
        opId: "529cafaf-e958-44f9-9b3c-02174ee46a9d",
        userArgs: {
          filters: [$ctx.auth.id]
        },
        cacheKey: `plasmic.$.529cafaf-e958-44f9-9b3c-02174ee46a9d.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicDiscipline.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicDiscipline.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicDiscipline.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          styleTokensClassNames,
          sty.root
        )}
      >
        <MenuNavigation
          data-plasmic-name={"menuNavigation"}
          data-plasmic-override={overrides.menuNavigation}
          className={classNames("__wab_instance", sty.menuNavigation)}
          firstName={generateStateValueProp($state, [
            "menuNavigation",
            "firstName"
          ])}
          headerLocationId={generateStateValueProp($state, [
            "menuNavigation",
            "headerLocationId"
          ])}
          lastName={generateStateValueProp($state, [
            "menuNavigation",
            "lastName"
          ])}
          onFirstNameChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "firstName"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onHeaderLocationIdChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "headerLocationId"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onLastNameChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "lastName"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          onUserRoleChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "menuNavigation",
              "userRole"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
          userRole={generateStateValueProp($state, [
            "menuNavigation",
            "userRole"
          ])}
        />

        <LoadingBoundary
          data-plasmic-name={"loadingBoundary"}
          data-plasmic-override={overrides.loadingBoundary}
          loadingState={
            <DataCtxReader__>
              {$ctx => (
                <LottieWrapper
                  data-plasmic-name={"lottie"}
                  data-plasmic-override={overrides.lottie}
                  animationData={{
                    nm: "Main Scene",
                    ddd: 0,
                    h: 540,
                    w: 540,
                    meta: { g: "@lottiefiles/creator 1.59.0" },
                    layers: [
                      {
                        ty: 4,
                        nm: "Dot4",
                        sr: 1,
                        st: 0,
                        op: 360,
                        ip: 0,
                        hd: false,
                        ddd: 0,
                        bm: 0,
                        hasMask: false,
                        ao: 0,
                        ks: {
                          a: { a: 0, k: [-284, 92, 0], ix: 1 },
                          s: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [31, 31],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [50, 50, 100],
                                t: 25
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [75, 75, 100],
                                t: 39
                              },
                              { s: [50, 50, 100], t: 55 }
                            ],
                            ix: 6
                          },
                          sk: { a: 0, k: 0 },
                          p: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [436, 270],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [452, 270],
                                t: 25
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [452, 230],
                                t: 39
                              },
                              { s: [452, 270], t: 55 }
                            ],
                            ix: 2
                          },
                          r: { a: 0, k: 0, ix: 10 },
                          sa: { a: 0, k: 0 },
                          o: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [25],
                                t: 25
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [100],
                                t: 39
                              },
                              { s: [25], t: 55 }
                            ],
                            ix: 11
                          }
                        },
                        shapes: [
                          {
                            ty: "gr",
                            bm: 0,
                            hd: false,
                            mn: "ADBE Vector Group",
                            nm: "Ellipse 1",
                            ix: 1,
                            cix: 2,
                            np: 3,
                            it: [
                              {
                                ty: "el",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Shape - Ellipse",
                                nm: "Ellipse Path 1",
                                d: 1,
                                p: { a: 0, k: [0, 0], ix: 3 },
                                s: { a: 0, k: [120, 120], ix: 2 }
                              },
                              {
                                ty: "fl",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Graphic - Fill",
                                nm: "Fill 1",
                                c: { a: 0, k: [0.1922, 0.4, 0.2902], ix: 4 },
                                r: 1,
                                o: { a: 0, k: 100, ix: 5 }
                              },
                              {
                                ty: "tr",
                                a: { a: 0, k: [0, 0], ix: 1 },
                                s: { a: 0, k: [100, 100], ix: 3 },
                                sk: { a: 0, k: 0, ix: 4 },
                                p: { a: 0, k: [-284, 92], ix: 2 },
                                r: { a: 0, k: 0, ix: 6 },
                                sa: { a: 0, k: 0, ix: 5 },
                                o: { a: 0, k: 100, ix: 7 }
                              }
                            ]
                          }
                        ],
                        ind: 1
                      },
                      {
                        ty: 4,
                        nm: "Dot3",
                        sr: 1,
                        st: 0,
                        op: 360,
                        ip: 0,
                        hd: false,
                        ddd: 0,
                        bm: 0,
                        hasMask: false,
                        ao: 0,
                        ks: {
                          a: { a: 0, k: [-284, 92, 0], ix: 1 },
                          s: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [31, 31],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [50, 50, 100],
                                t: 17
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [75, 75, 100],
                                t: 31
                              },
                              { s: [50, 50, 100], t: 47 }
                            ],
                            ix: 6
                          },
                          sk: { a: 0, k: 0 },
                          p: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [324, 270],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [332, 270],
                                t: 17
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [332, 230],
                                t: 31
                              },
                              { s: [332, 270], t: 47 }
                            ],
                            ix: 2
                          },
                          r: { a: 0, k: 0, ix: 10 },
                          sa: { a: 0, k: 0 },
                          o: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [25],
                                t: 17
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [100],
                                t: 31
                              },
                              { s: [25], t: 47 }
                            ],
                            ix: 11
                          }
                        },
                        shapes: [
                          {
                            ty: "gr",
                            bm: 0,
                            hd: false,
                            mn: "ADBE Vector Group",
                            nm: "Ellipse 1",
                            ix: 1,
                            cix: 2,
                            np: 3,
                            it: [
                              {
                                ty: "el",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Shape - Ellipse",
                                nm: "Ellipse Path 1",
                                d: 1,
                                p: { a: 0, k: [0, 0], ix: 3 },
                                s: { a: 0, k: [120, 120], ix: 2 }
                              },
                              {
                                ty: "fl",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Graphic - Fill",
                                nm: "Fill 1",
                                c: { a: 0, k: [0.1922, 0.4, 0.2902], ix: 4 },
                                r: 1,
                                o: { a: 0, k: 100, ix: 5 }
                              },
                              {
                                ty: "tr",
                                a: { a: 0, k: [0, 0], ix: 1 },
                                s: { a: 0, k: [100, 100], ix: 3 },
                                sk: { a: 0, k: 0, ix: 4 },
                                p: { a: 0, k: [-284, 92], ix: 2 },
                                r: { a: 0, k: 0, ix: 6 },
                                sa: { a: 0, k: 0, ix: 5 },
                                o: { a: 0, k: 100, ix: 7 }
                              }
                            ]
                          }
                        ],
                        ind: 2
                      },
                      {
                        ty: 4,
                        nm: "Dot2",
                        sr: 1,
                        st: 0,
                        op: 360,
                        ip: 0,
                        hd: false,
                        ddd: 0,
                        bm: 0,
                        hasMask: false,
                        ao: 0,
                        ks: {
                          a: { a: 0, k: [-284, 92, 0], ix: 1 },
                          s: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [31, 31],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [50, 50, 100],
                                t: 9
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [75, 75, 100],
                                t: 23
                              },
                              { s: [50, 50, 100], t: 39 }
                            ],
                            ix: 6
                          },
                          sk: { a: 0, k: 0 },
                          p: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [220, 270],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [212, 270],
                                t: 9
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [212, 230],
                                t: 23
                              },
                              { s: [212, 270], t: 39 }
                            ],
                            ix: 2
                          },
                          r: { a: 0, k: 0, ix: 10 },
                          sa: { a: 0, k: 0 },
                          o: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [25],
                                t: 9
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [100],
                                t: 23
                              },
                              { s: [25], t: 39 }
                            ],
                            ix: 11
                          }
                        },
                        shapes: [
                          {
                            ty: "gr",
                            bm: 0,
                            hd: false,
                            mn: "ADBE Vector Group",
                            nm: "Ellipse 1",
                            ix: 1,
                            cix: 2,
                            np: 3,
                            it: [
                              {
                                ty: "el",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Shape - Ellipse",
                                nm: "Ellipse Path 1",
                                d: 1,
                                p: { a: 0, k: [0, 0], ix: 3 },
                                s: { a: 0, k: [120, 120], ix: 2 }
                              },
                              {
                                ty: "fl",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Graphic - Fill",
                                nm: "Fill 1",
                                c: { a: 0, k: [0.1922, 0.4, 0.2902], ix: 4 },
                                r: 1,
                                o: { a: 0, k: 100, ix: 5 }
                              },
                              {
                                ty: "tr",
                                a: { a: 0, k: [0, 0], ix: 1 },
                                s: { a: 0, k: [100, 100], ix: 3 },
                                sk: { a: 0, k: 0, ix: 4 },
                                p: { a: 0, k: [-284, 92], ix: 2 },
                                r: { a: 0, k: 0, ix: 6 },
                                sa: { a: 0, k: 0, ix: 5 },
                                o: { a: 0, k: 100, ix: 7 }
                              }
                            ]
                          }
                        ],
                        ind: 3
                      },
                      {
                        ty: 4,
                        nm: "Dot1",
                        sr: 1,
                        st: 0,
                        op: 360,
                        ip: 0,
                        hd: false,
                        ddd: 0,
                        bm: 0,
                        hasMask: false,
                        ao: 0,
                        ks: {
                          a: { a: 0, k: [-284, 92, 0], ix: 1 },
                          s: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [50, 50, 100],
                                t: 0
                              },
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [32.386446959656624, 32.386446959656624],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [75, 75, 100],
                                t: 14
                              },
                              { s: [50, 50, 100], t: 30 }
                            ],
                            ix: 6
                          },
                          sk: { a: 0, k: 0 },
                          p: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [92, 270],
                                t: 0
                              },
                              {
                                o: { x: 0.167, y: 0.167 },
                                i: { x: 0.833, y: 0.833 },
                                s: [108, 270],
                                t: 2
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [92, 230],
                                t: 14
                              },
                              { s: [92, 270], t: 30 }
                            ],
                            ix: 2
                          },
                          r: { a: 0, k: 0, ix: 10 },
                          sa: { a: 0, k: 0 },
                          o: {
                            a: 1,
                            k: [
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [25],
                                t: 0
                              },
                              {
                                o: { x: 0.333, y: 0 },
                                i: { x: 0.667, y: 1 },
                                s: [100],
                                t: 14
                              },
                              { s: [25], t: 30 }
                            ],
                            ix: 11
                          }
                        },
                        shapes: [
                          {
                            ty: "gr",
                            bm: 0,
                            hd: false,
                            mn: "ADBE Vector Group",
                            nm: "Ellipse 1",
                            ix: 1,
                            cix: 2,
                            np: 3,
                            it: [
                              {
                                ty: "el",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Shape - Ellipse",
                                nm: "Ellipse Path 1",
                                d: 1,
                                p: { a: 0, k: [0, 0], ix: 3 },
                                s: { a: 0, k: [120, 120], ix: 2 }
                              },
                              {
                                ty: "fl",
                                bm: 0,
                                hd: false,
                                mn: "ADBE Vector Graphic - Fill",
                                nm: "Fill 1",
                                c: { a: 0, k: [0.1922, 0.4, 0.2902], ix: 4 },
                                r: 1,
                                o: { a: 0, k: 100, ix: 5 }
                              },
                              {
                                ty: "tr",
                                a: { a: 0, k: [0, 0], ix: 1 },
                                s: { a: 0, k: [100, 100], ix: 3 },
                                sk: { a: 0, k: 0, ix: 4 },
                                p: { a: 0, k: [-284, 92], ix: 2 },
                                r: { a: 0, k: 0, ix: 6 },
                                sa: { a: 0, k: 0, ix: 5 },
                                o: { a: 0, k: 100, ix: 7 }
                              }
                            ]
                          }
                        ],
                        ind: 4
                      }
                    ],
                    v: "5.7.0",
                    fr: 60,
                    op: 81,
                    ip: 0,
                    assets: []
                  }}
                  className={classNames("__wab_instance", sty.lottie)}
                  preview={true}
                />
              )}
            </DataCtxReader__>
          }
        >
          <DataCtxReader__>
            {$ctx => (
              <RedirectIf
                data-plasmic-name={"redirectIf"}
                data-plasmic-override={overrides.redirectIf}
                className={classNames("__wab_instance", sty.redirectIf)}
                condition={true}
                onFalse={async () => {
                  const $steps = {};

                  $steps["goToLoginPage"] = true
                    ? (() => {
                        const actionArgs = { destination: `/auth/login` };
                        return (({ destination }) => {
                          if (
                            typeof destination === "string" &&
                            destination.startsWith("#")
                          ) {
                            document
                              .getElementById(destination.substr(1))
                              .scrollIntoView({ behavior: "smooth" });
                          } else {
                            __nextRouter?.push(destination);
                          }
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["goToLoginPage"] != null &&
                    typeof $steps["goToLoginPage"] === "object" &&
                    typeof $steps["goToLoginPage"].then === "function"
                  ) {
                    $steps["goToLoginPage"] = await $steps["goToLoginPage"];
                  }
                }}
              >
                <div className={classNames(projectcss.all, sty.freeBox__jtUkZ)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ureDb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__nlSty)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mKhGx
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wQDeC
                          )}
                        >
                          {"APS Dashboard"}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__c457R
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8HOob
                          )}
                        >
                          {
                            "Here\u2019s your organization's current discipline health. Click a Team Member to see their recent infractions."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lKzxl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cHwGk)}
                  >
                    <div
                      data-plasmic-name={"verticalStack"}
                      data-plasmic-override={overrides.verticalStack}
                      className={classNames(projectcss.all, sty.verticalStack)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__of8Zu
                        )}
                      >
                        {"Employees"}
                      </div>
                      <DisciplineTable
                        data-plasmic-name={"disciplineTable"}
                        data-plasmic-override={overrides.disciplineTable}
                        className={classNames(
                          "__wab_instance",
                          sty.disciplineTable
                        )}
                        density={"comfortable"}
                        locationId={"67e00fb2-29f5-41ce-9c1c-93e2f7f392dd"}
                        onRowClick={async employee => {
                          const $steps = {};

                          $steps["updateSelectedEmployee"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["selectedEmployee"]
                                  },
                                  operation: 0,
                                  value: employee
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateSelectedEmployee"] != null &&
                            typeof $steps["updateSelectedEmployee"] ===
                              "object" &&
                            typeof $steps["updateSelectedEmployee"].then ===
                              "function"
                          ) {
                            $steps["updateSelectedEmployee"] =
                              await $steps["updateSelectedEmployee"];
                          }

                          $steps["updateDrawerOpen"] = true
                            ? (() => {
                                const actionArgs = {
                                  variable: {
                                    objRoot: $state,
                                    variablePath: ["drawerOpen"]
                                  },
                                  operation: 0,
                                  value: true
                                };
                                return (({
                                  variable,
                                  value,
                                  startIndex,
                                  deleteCount
                                }) => {
                                  if (!variable) {
                                    return;
                                  }
                                  const { objRoot, variablePath } = variable;

                                  $stateSet(objRoot, variablePath, value);
                                  return value;
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["updateDrawerOpen"] != null &&
                            typeof $steps["updateDrawerOpen"] === "object" &&
                            typeof $steps["updateDrawerOpen"].then ===
                              "function"
                          ) {
                            $steps["updateDrawerOpen"] =
                              await $steps["updateDrawerOpen"];
                          }
                        }}
                        orgId={"54b9864f-9df9-4a15-a209-7b99e1c274f4"}
                        showActions={true}
                      />
                    </div>
                    <div
                      data-plasmic-name={"verticalStack2"}
                      data-plasmic-override={overrides.verticalStack2}
                      className={classNames(projectcss.all, sty.verticalStack2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oSxFd
                        )}
                      >
                        {"Disciplinary Actions"}
                      </div>
                      <DisciplineActionsTable
                        data-plasmic-name={"disciplineActionsTable"}
                        data-plasmic-override={overrides.disciplineActionsTable}
                        className={classNames(
                          "__wab_instance",
                          sty.disciplineActionsTable
                        )}
                        density={"comfortable"}
                        locationId={"67e00fb2-29f5-41ce-9c1c-93e2f7f392dd"}
                        orgId={"54b9864f-9df9-4a15-a209-7b99e1c274f4"}
                        showActions={false}
                      />
                    </div>
                  </div>
                </div>
                <MuiDrawerV2
                  data-plasmic-name={"drawerV2Mui"}
                  data-plasmic-override={overrides.drawerV2Mui}
                  autoFocus={true}
                  className={classNames("__wab_instance", sty.drawerV2Mui)}
                  closable={true}
                  destroyOnClose={false}
                  keyboard={true}
                  mask={true}
                  maskClosable={true}
                  onOpenChange={async (...eventArgs: any) => {
                    generateStateOnChangeProp($state, [
                      "drawerV2Mui",
                      "open"
                    ]).apply(null, eventArgs);

                    (async open => {
                      const $steps = {};

                      $steps["updateDrawerOpen"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["drawerOpen"]
                              },
                              operation: 0,
                              value: true
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDrawerOpen"] != null &&
                        typeof $steps["updateDrawerOpen"] === "object" &&
                        typeof $steps["updateDrawerOpen"].then === "function"
                      ) {
                        $steps["updateDrawerOpen"] =
                          await $steps["updateDrawerOpen"];
                      }
                    }).apply(null, eventArgs);
                  }}
                  open={generateStateValueProp($state, ["drawerV2Mui", "open"])}
                  placement={"right"}
                  size={"default"}
                  title={
                    <div
                      data-plasmic-name={"content3"}
                      data-plasmic-override={overrides.content3}
                      className={classNames(projectcss.all, sty.content3)}
                    >
                      <div
                        data-plasmic-name={"textAndSupportingText3"}
                        data-plasmic-override={overrides.textAndSupportingText3}
                        className={classNames(
                          projectcss.all,
                          sty.textAndSupportingText3
                        )}
                      >
                        <div
                          data-plasmic-name={"textAndOnlineIndicator2"}
                          data-plasmic-override={
                            overrides.textAndOnlineIndicator2
                          }
                          className={classNames(
                            projectcss.all,
                            sty.textAndOnlineIndicator2
                          )}
                        >
                          <div
                            data-plasmic-name={"text3"}
                            data-plasmic-override={overrides.text3}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text3
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    {
                                      {
                                        return $state.selectedEmployee
                                          ?.full_name;
                                      }
                                    }
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "Reece Howard";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"supportingText3"}
                          data-plasmic-override={overrides.supportingText3}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.supportingText3
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $state.selectedEmployee?.role;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Owner/Operator";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                  }
                  width={"620"}
                  zIndex={1000}
                >
                  <DrawerTabContainer
                    data-plasmic-name={"drawerTabContainer"}
                    data-plasmic-override={overrides.drawerTabContainer}
                    className={classNames(
                      "__wab_instance",
                      sty.drawerTabContainer
                    )}
                    employee={(() => {
                      try {
                        return $state.selectedEmployee;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    initialTab={"discipline"}
                    onRecordAction={async () => {
                      const $steps = {};

                      $steps["runCode"] = true
                        ? (() => {
                            const actionArgs = {
                              customFunction: async () => {
                                return () =>
                                  ($state.recordActionModalOpen = true);
                              }
                            };
                            return (({ customFunction }) => {
                              return customFunction();
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["runCode"] != null &&
                        typeof $steps["runCode"] === "object" &&
                        typeof $steps["runCode"].then === "function"
                      ) {
                        $steps["runCode"] = await $steps["runCode"];
                      }
                    }}
                    orgId={(() => {
                      try {
                        return $ctx.auth.org_id;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                </MuiDrawerV2>
              </RedirectIf>
            )}
          </DataCtxReader__>
        </LoadingBoundary>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "menuNavigation",
    "loadingBoundary",
    "lottie",
    "redirectIf",
    "verticalStack",
    "disciplineTable",
    "verticalStack2",
    "disciplineActionsTable",
    "drawerV2Mui",
    "drawerTabContainer",
    "content3",
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  menuNavigation: ["menuNavigation"],
  loadingBoundary: [
    "loadingBoundary",
    "lottie",
    "redirectIf",
    "verticalStack",
    "disciplineTable",
    "verticalStack2",
    "disciplineActionsTable",
    "drawerV2Mui",
    "drawerTabContainer",
    "content3",
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  lottie: ["lottie"],
  redirectIf: [
    "redirectIf",
    "verticalStack",
    "disciplineTable",
    "verticalStack2",
    "disciplineActionsTable",
    "drawerV2Mui",
    "drawerTabContainer",
    "content3",
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  verticalStack: ["verticalStack", "disciplineTable"],
  disciplineTable: ["disciplineTable"],
  verticalStack2: ["verticalStack2", "disciplineActionsTable"],
  disciplineActionsTable: ["disciplineActionsTable"],
  drawerV2Mui: [
    "drawerV2Mui",
    "drawerTabContainer",
    "content3",
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  drawerTabContainer: ["drawerTabContainer"],
  content3: [
    "content3",
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  textAndSupportingText3: [
    "textAndSupportingText3",
    "textAndOnlineIndicator2",
    "text3",
    "supportingText3"
  ],
  textAndOnlineIndicator2: ["textAndOnlineIndicator2", "text3"],
  text3: ["text3"],
  supportingText3: ["supportingText3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  menuNavigation: typeof MenuNavigation;
  loadingBoundary: typeof LoadingBoundary;
  lottie: typeof LottieWrapper;
  redirectIf: typeof RedirectIf;
  verticalStack: "div";
  disciplineTable: typeof DisciplineTable;
  verticalStack2: "div";
  disciplineActionsTable: typeof DisciplineActionsTable;
  drawerV2Mui: typeof MuiDrawerV2;
  drawerTabContainer: typeof DrawerTabContainer;
  content3: "div";
  textAndSupportingText3: "div";
  textAndOnlineIndicator2: "div";
  text3: "div";
  supportingText3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDiscipline__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDiscipline__VariantsArgs;
    args?: PlasmicDiscipline__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDiscipline__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDiscipline__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDiscipline__ArgProps,
          internalVariantPropNames: PlasmicDiscipline__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDiscipline__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDiscipline";
  } else {
    func.displayName = `PlasmicDiscipline.${nodeName}`;
  }
  return func;
}

export const PlasmicDiscipline = Object.assign(
  // Top-level PlasmicDiscipline renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    menuNavigation: makeNodeComponent("menuNavigation"),
    loadingBoundary: makeNodeComponent("loadingBoundary"),
    lottie: makeNodeComponent("lottie"),
    redirectIf: makeNodeComponent("redirectIf"),
    verticalStack: makeNodeComponent("verticalStack"),
    disciplineTable: makeNodeComponent("disciplineTable"),
    verticalStack2: makeNodeComponent("verticalStack2"),
    disciplineActionsTable: makeNodeComponent("disciplineActionsTable"),
    drawerV2Mui: makeNodeComponent("drawerV2Mui"),
    drawerTabContainer: makeNodeComponent("drawerTabContainer"),
    content3: makeNodeComponent("content3"),
    textAndSupportingText3: makeNodeComponent("textAndSupportingText3"),
    textAndOnlineIndicator2: makeNodeComponent("textAndOnlineIndicator2"),
    text3: makeNodeComponent("text3"),
    supportingText3: makeNodeComponent("supportingText3"),

    // Metadata about props expected for PlasmicDiscipline
    internalVariantProps: PlasmicDiscipline__VariantProps,
    internalArgProps: PlasmicDiscipline__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "APS Dashboard | Levelset",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicDiscipline;
/* prettier-ignore-end */
