/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eNCsaJXBZ9ykYnmvxCb8Zx
// Component: DnrJ08NISsSS

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../levelset_v2/plasmic_levelset_v2.module.css"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectcss
import sty from "./PlasmicDashboardSubmenu.module.css"; // plasmic-import: DnrJ08NISsSS/css

createPlasmicElementProxy;

export type PlasmicDashboardSubmenu__VariantMembers = {};
export type PlasmicDashboardSubmenu__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboardSubmenu__VariantsArgs;
export const PlasmicDashboardSubmenu__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDashboardSubmenu__ArgsType = {};
type ArgPropType = keyof PlasmicDashboardSubmenu__ArgsType;
export const PlasmicDashboardSubmenu__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboardSubmenu__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultDashboardSubmenuProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDashboardSubmenu__RenderFunc(props: {
  variants: PlasmicDashboardSubmenu__VariantsArgs;
  args: PlasmicDashboardSubmenu__ArgsType;
  overrides: PlasmicDashboardSubmenu__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__lx5Gj)}>
        <div className={classNames(projectcss.all, sty.freeBox___5Vowa)}>
          <AntdButton
            className={classNames("__wab_instance", sty.button__ouwyl)}
            ghost={false}
            loading={false}
            shape={"default"}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__akSkk
              )}
            >
              {"Pathway"}
            </div>
          </AntdButton>
          <AntdButton
            className={classNames("__wab_instance", sty.button__fzAcG)}
            onClick={async () => {
              const $steps = {};

              $steps["goToPea"] = true
                ? (() => {
                    const actionArgs = {
                      destination: `/positional-excellence`
                    };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToPea"] != null &&
                typeof $steps["goToPea"] === "object" &&
                typeof $steps["goToPea"].then === "function"
              ) {
                $steps["goToPea"] = await $steps["goToPea"];
              }
            }}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__i5EJo
              )}
            >
              {"PEA"}
            </div>
          </AntdButton>
          <AntdButton
            className={classNames("__wab_instance", sty.button__elre)}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vkIxh
              )}
            >
              {"Evaluations"}
            </div>
          </AntdButton>
          <AntdButton
            className={classNames("__wab_instance", sty.button__tGzU)}
            danger={false}
            ghost={false}
            href={`/discipline`}
            loading={false}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tyFVx
              )}
            >
              {"APS"}
            </div>
          </AntdButton>
          <AntdButton
            className={classNames("__wab_instance", sty.button___3Cma9)}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b1N0E
              )}
            >
              {"WHED"}
            </div>
          </AntdButton>
          <AntdButton
            className={classNames("__wab_instance", sty.button__flfMl)}
            type={"ghost"}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rin15
              )}
            >
              {"360\u00b0\u00a0Overview"}
            </div>
          </AntdButton>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboardSubmenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboardSubmenu__VariantsArgs;
    args?: PlasmicDashboardSubmenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDashboardSubmenu__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDashboardSubmenu__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboardSubmenu__ArgProps,
          internalVariantPropNames: PlasmicDashboardSubmenu__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDashboardSubmenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDashboardSubmenu";
  } else {
    func.displayName = `PlasmicDashboardSubmenu.${nodeName}`;
  }
  return func;
}

export const PlasmicDashboardSubmenu = Object.assign(
  // Top-level PlasmicDashboardSubmenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDashboardSubmenu
    internalVariantProps: PlasmicDashboardSubmenu__VariantProps,
    internalArgProps: PlasmicDashboardSubmenu__ArgProps
  }
);

export default PlasmicDashboardSubmenu;
/* prettier-ignore-end */
