/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eNCsaJXBZ9ykYnmvxCb8Zx
// Component: UwKJxxQFYiGw

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SupabaseUserLogOut } from "../../CodeComponents/auth/SupabaseUserLogOut"; // plasmic-import: l-xO2VjafQ7l/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../levelset_v2/plasmic_levelset_v2.module.css"; // plasmic-import: eNCsaJXBZ9ykYnmvxCb8Zx/projectcss
import sty from "./PlasmicLogoutButton.module.css"; // plasmic-import: UwKJxxQFYiGw/css

createPlasmicElementProxy;

export type PlasmicLogoutButton__VariantMembers = {
  logoutHover: "logoutHover";
};
export type PlasmicLogoutButton__VariantsArgs = {
  logoutHover?: SingleBooleanChoiceArg<"logoutHover">;
};
type VariantPropType = keyof PlasmicLogoutButton__VariantsArgs;
export const PlasmicLogoutButton__VariantProps = new Array<VariantPropType>(
  "logoutHover"
);

export type PlasmicLogoutButton__ArgsType = { slot3?: React.ReactNode };
type ArgPropType = keyof PlasmicLogoutButton__ArgsType;
export const PlasmicLogoutButton__ArgProps = new Array<ArgPropType>("slot3");

export type PlasmicLogoutButton__OverridesType = {
  root?: Flex__<typeof SupabaseUserLogOut>;
  freeBox?: Flex__<"div">;
};

export interface DefaultLogoutButtonProps {
  slot3?: React.ReactNode;
  logoutHover?: SingleBooleanChoiceArg<"logoutHover">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLogoutButton__RenderFunc(props: {
  variants: PlasmicLogoutButton__VariantsArgs;
  args: PlasmicLogoutButton__ArgsType;
  overrides: PlasmicLogoutButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "logoutHover",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.logoutHover
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <SupabaseUserLogOut
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootlogoutHover]: hasVariant(
            $state,
            "logoutHover",
            "logoutHover"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxlogoutHover]: hasVariant(
            $state,
            "logoutHover",
            "logoutHover"
          )
        })}
        onMouseEnter={async event => {
          const $steps = {};

          $steps["updateLogoutHover"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "logoutHover",
                  operation: 2,
                  value: "logoutHover"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateLogoutHover"] != null &&
            typeof $steps["updateLogoutHover"] === "object" &&
            typeof $steps["updateLogoutHover"].then === "function"
          ) {
            $steps["updateLogoutHover"] = await $steps["updateLogoutHover"];
          }
        }}
        onMouseLeave={async event => {
          const $steps = {};

          $steps["updateLogoutHover"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "logoutHover",
                  operation: 2,
                  value: "logoutHover"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateLogoutHover"] != null &&
            typeof $steps["updateLogoutHover"] === "object" &&
            typeof $steps["updateLogoutHover"].then === "function"
          ) {
            $steps["updateLogoutHover"] = await $steps["updateLogoutHover"];
          }
        }}
      >
        {renderPlasmicSlot({
          defaultContents: "Log Out",
          value: args.slot3,
          className: classNames(sty.slotTargetSlot3, {
            [sty.slotTargetSlot3logoutHover]: hasVariant(
              $state,
              "logoutHover",
              "logoutHover"
            )
          })
        })}
      </div>
    </SupabaseUserLogOut>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof SupabaseUserLogOut;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLogoutButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLogoutButton__VariantsArgs;
    args?: PlasmicLogoutButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLogoutButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLogoutButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLogoutButton__ArgProps,
          internalVariantPropNames: PlasmicLogoutButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLogoutButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoutButton";
  } else {
    func.displayName = `PlasmicLogoutButton.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoutButton = Object.assign(
  // Top-level PlasmicLogoutButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicLogoutButton
    internalVariantProps: PlasmicLogoutButton__VariantProps,
    internalArgProps: PlasmicLogoutButton__ArgProps
  }
);

export default PlasmicLogoutButton;
/* prettier-ignore-end */
