/**
 * POST /api/onboarding/invite-leaders
 *
 * Creates invite records and sends invitation emails to leaders.
 * Called during onboarding Step 7.
 *
 * Auth: Bearer token from Supabase Auth session.
 */

import type { NextApiRequest, NextApiResponse } from 'next';
import { createServerSupabaseClient } from '@/lib/supabase-server';
import { sendLeaderInviteEmail } from '@/lib/emails/leader-invite';

interface InviteInput {
  employeeId: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const supabase = createServerSupabaseClient();

  // Verify auth
  const token = req.headers.authorization?.replace('Bearer ', '');
  if (!token) return res.status(401).json({ error: 'Unauthorized' });

  const { data: { user }, error: authError } = await supabase.auth.getUser(token);
  if (authError || !user) return res.status(401).json({ error: 'Invalid token' });

  const { data: appUser } = await supabase
    .from('app_users')
    .select('id, org_id, first_name, last_name')
    .eq('auth_user_id', user.id)
    .maybeSingle();

  if (!appUser?.org_id) {
    return res.status(403).json({ error: 'Complete account setup first' });
  }

  const { invites } = req.body as { invites: InviteInput[] };

  if (!invites || !Array.isArray(invites) || invites.length === 0) {
    return res.status(400).json({ error: 'invites array is required' });
  }

  try {
    // Get org name for the email
    const { data: org } = await supabase
      .from('orgs')
      .select('name')
      .eq('id', appUser.org_id)
      .single();

    const orgName = org?.name || 'your organization';
    const inviterName = `${appUser.first_name || ''} ${appUser.last_name || ''}`.trim() || 'Your team';

    let sentCount = 0;
    const errors: string[] = [];

    for (const invite of invites) {
      try {
        // Find the employee record (may have been inserted in Step 6)
        let employeeId: string | null = null;

        // Try to find the employee by name match in this org
        const { data: employee } = await supabase
          .from('employees')
          .select('id')
          .eq('org_id', appUser.org_id)
          .eq('first_name', invite.firstName)
          .eq('last_name', invite.lastName)
          .maybeSingle();

        if (employee) {
          employeeId = employee.id;
        }

        // Create invite record (token auto-generated by DB default)
        const { data: inviteRecord, error: inviteError } = await supabase
          .from('onboarding_invites')
          .insert({
            org_id: appUser.org_id,
            employee_id: employeeId,
            email: invite.email,
            first_name: invite.firstName,
            last_name: invite.lastName,
            role: invite.role,
            invited_by: appUser.id,
          })
          .select('id, token')
          .single();

        if (inviteError || !inviteRecord) {
          throw new Error(inviteError?.message || 'Failed to create invite');
        }

        // Send invite email
        await sendLeaderInviteEmail({
          to: invite.email,
          firstName: invite.firstName,
          inviterName,
          orgName,
          roleName: invite.role,
          inviteToken: inviteRecord.token,
        });

        sentCount++;
      } catch (err: any) {
        console.error(`Failed to invite ${invite.email}:`, err);
        errors.push(`${invite.firstName} ${invite.lastName}: ${err.message}`);
      }
    }

    return res.status(200).json({
      success: true,
      sentCount,
      totalInvites: invites.length,
      errors: errors.length > 0 ? errors : undefined,
    });
  } catch (err: any) {
    console.error('invite-leaders error:', err);
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
