/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5ZtnypMovRHeeP3YTdPCYL

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantscqh1YWTrsJfR } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: CQH1yWTrsJfR/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantscqh1YWTrsJfR
});
