/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4vjRXvnb4XuY6J15w9oRcQ

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantssunYRowGfPxL } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: sunYRowGFPxL/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantssunYRowGfPxL
});
